---
book_repo: pivotal-cf/docs-book-concourse-olm
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: edge
feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
# cross-product resources
- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: concourse/partials
  no_docs: true
- repository:
    name: pivotal-cf/docs-concourse-olm
    ref: 'master'
  directory: p-concourse/6-x
  subnav_template: concourse-olm-subnav-6-x.erb
  product_info:
    use_local_header: true
    latest_stable_version: 5.2.0
    changelog_href: https://docs.pivotal.io/p-concourse/6-x/rn.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Concourse for PCF
    search_placeholder: Search Concourse for PCF 6.0
    url_prefix: p-concourse/6-x
    local_product_version: 6.0
    local_header_links: []
    local_header_version_list:
