---
book_repo: pivotal-cf/docs-book-concourse-olm
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
- repository:
    name: pivotal-cf/docs-concourse-olm
    ref: '3.x'
  directory: p-concourse
  subnav_template: concourse-olm-subnav.erb


