---
book_repo: pivotal-cf/docs-book-concourse-olm
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-concourse-olm
    ref: '4.x'
  directory: p-concourse/4-0
  subnav_template: concourse-olm-subnav-4-0.erb
  product_info:
    use_local_header: true
    latest_stable_version: "4.0"
    changelog_href: https://docs.pivotal.io/p-concourse/4-0/rn.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Concourse for PCF
    search_placeholder: Search Concourse for PCF 4.0
    url_prefix: p-concourse/4-0
    local_product_version: "v4"
    local_header_links: []
    local_header_version_list:
          - url_prefix: http://docs.pivotal.io/p-concourse/3-0
            display_name: v3

- repository:
    name: pivotal-cf/docs-concourse-olm
    ref: '3.x'
  directory: p-concourse/3-0
  subnav_template: concourse-olm-subnav-3-0.erb
  product_info:
    use_local_header: true
    latest_stable_version: "4.0"
    changelog_href: https://docs.pivotal.io/p-concourse/3-0/rn.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Concourse for PCF
    search_placeholder: Search Concourse v3
    url_prefix: p-concourse/3-0
    local_product_version: "v3"
    local_header_links: []
    local_header_version_list:
          - url_prefix: http://docs.pivotal.io/p-concourse/4-0
            display_name: v4

