---
book_repo: pivotal-cf/docs-book-concourse-olm
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
# cross-product resources
- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: concourse/partials
  no_docs: true

- repository:
    name: pivotal-cf/docs-concourse-olm
    ref: '5.x'
  directory: p-concourse/5-x
  subnav_template: concourse-olm-subnav-5-x.erb
  product_info:
    use_local_header: true
    latest_stable_version: 5.2.0
    changelog_href: https://docs.pivotal.io/p-concourse/5-x/rn.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Concourse for PCF
    search_placeholder: Search Concourse for PCF v5.x
    url_prefix: p-concourse/5-x
    local_product_version: 5.x
    local_header_links: []
    local_header_version_list:
          - url_prefix: http://docs.pivotal.io/p-concourse/4-x
            display_name: 4.x
          - url_prefix: http://docs.pivotal.io/p-concourse/3-x
            display_name: 3.x

- repository:
    name: pivotal-cf/docs-concourse-olm
    ref: '4.x'
  directory: p-concourse/4-x
  subnav_template: concourse-olm-subnav-4-x.erb
  product_info:
    use_local_header: true
    latest_stable_version: 5.2.0
    changelog_href: https://docs.pivotal.io/p-concourse/4-x/rn.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Concourse for PCF
    search_placeholder: Search Concourse for PCF v4.x
    url_prefix: p-concourse/4-x
    local_product_version: 4.x
    local_header_links: []
    local_header_version_list:
          - url_prefix: http://docs.pivotal.io/p-concourse/5-x
            display_name: 5.x
          - url_prefix: http://docs.pivotal.io/p-concourse/3-x
            display_name: 3.x

- repository:
    name: pivotal-cf/docs-concourse-olm
    ref: '3.x'
  directory: p-concourse/3-x
  subnav_template: concourse-olm-subnav-3-x.erb
  product_info:
    use_local_header: true
    latest_stable_version: 5.2.0
    changelog_href: https://docs.pivotal.io/p-concourse/3-x/rn.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Concourse for PCF
    search_placeholder: Search Concourse for PCF v3.x
    url_prefix: p-concourse/3-x
    local_product_version: 3.x
    local_header_links: []
    local_header_version_list:
          - url_prefix: http://docs.pivotal.io/p-concourse/5-x
            display_name: 5.x
          - url_prefix: http://docs.pivotal.io/p-concourse/4-x
            display_name: 4.x
